spring:
  application:
    name: razorpay
  datasource:
    url: jdbc:postgresql://localhost:5432/razorpay_clone
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

vault:
  master-key: alakwfchwekl4kfsnf4wnlsdnmvl349jvlsdkmvsldjn342ikvnsldnmvsdlj23409k

payment:
  simulator:
    poll-interval-ms: 5000
    chaos-mode: NORMAL
    method:
      CARD:
        min-delay-seconds: 2
        max-delay-seconds: 6
        success-rate: 90
      UPI:
        min-delay-seconds: 1
        max-delay-seconds: 3
        success-rate: 95
      NET_BANKING:
        min-delay-seconds: 4
        max-delay-seconds: 10
        success-rate: 80

jwt:
  secret-key: dont-use-in-prod-deibrvjvbeiuoiuyr3498599fsudheih2398ryrh34r34irh3irh3rhk3fh34r4wfi34